# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Gorm Tools Grails Plugin
description: Plugin tools Grails/Gorm - repository data services, json query language, fast data binder
author: Yak.Works
group: org.grails.plugins

github:
  fullName: yakworks/gorm-tools

team:
  developers: ['basejump: Joshua Burnett', 'snimavat: Sudhir Nimavat', 'alexeyzvegintcev: Alexey']

bintray:
  enabled: true
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots
